---
name: Test-Perl-Critic-Progressive
version: 0.02
author:
  - 'Jeffrey Thalhammer <thaljef@cpan.org>'
abstract: Use Perl::Critic in test scripts
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Perl::Critic: 0.21
  Perl::Critic::Utils: 0.21
  Test::Builder: 0
build_requires:
  Test::More: 0
provides:
  Test::Perl::Critic::Progressive:
    file: lib/Test/Perl/Critic/Progressive.pm
    version: 0.02
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
